version: '3.8'

services:
  bubaclipper:
    build: .
    container_name: bubaclipper
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./:/app/media_data
    environment:
      - PYTHONUNBUFFERED=1
